import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const urbanist = Urbanist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
     <body className={`${urbanist.className} bg-slate-900 text-slate-100`}>
         <Header/>
        {children}
       <div className="h-[2vh]"></div>   
       <Footer/> 
   
  <div
  className="
    pointer-events-none fixed inset-0 z-0 flex items-center justify-center
  "
>
  <div
    className="
      mt-[-220px] h-[900px] w-[900px] rounded-full
      bg-[radial-gradient(circle,rgba(59,130,246,0.32)_0%,rgba(59,130,246,0.16)_38%,rgba(2,6,23,0)_74%)]
      blur-[50px] opacity-88
    "
  />
</div>
      
      <div
       className="fixed pointer-events-none inset-0 -z-10 h-full opacity-10 mix-blend-soft-light"
       style={{
       backgroundImage: "url('/noise-texture.jpg')",
       }}
      />  
       </body>
    </html>
  );
}









